package rules;

import com.ftn.sbnz.f1.model.enums.DriverIssue;
import com.ftn.sbnz.f1.model.enums.FlagStatus;
import com.ftn.sbnz.f1.model.facts.BatteryHigh;
import com.ftn.sbnz.f1.model.facts.CarTelemetry;
import com.ftn.sbnz.f1.model.facts.CompetitorStatus;
import com.ftn.sbnz.f1.model.facts.DriverReport;
import com.ftn.sbnz.f1.model.facts.ErsOvertakeAvailable;
import com.ftn.sbnz.f1.model.facts.FullResourceDefense;
import com.ftn.sbnz.f1.model.facts.OvertakeOpportunity;
import com.ftn.sbnz.f1.model.facts.PaceDropDetected;
import com.ftn.sbnz.f1.model.facts.PossibleSuspensionDamage;
import com.ftn.sbnz.f1.model.facts.RaceState;
import com.ftn.sbnz.f1.model.facts.SuspensionCheckRequired;
import com.ftn.sbnz.f1.model.facts.SuspensionStatus;
import com.ftn.sbnz.f1.model.facts.TrackStatus;
import com.ftn.sbnz.f1.model.facts.TyresWorn;
import com.ftn.sbnz.f1.model.facts.WeakCarPerformance;

rule "Detect overtake opportunity"
when
    CompetitorStatus(gapAheadSeconds < 1.0)
    TrackStatus(flagStatus == FlagStatus.GREEN)
    not OvertakeOpportunity()
then
    insertLogical(new OvertakeOpportunity());
end

rule "Detect high battery"
when
    CarTelemetry(ersBatteryPercentage > 50)
    not BatteryHigh()
then
    insertLogical(new BatteryHigh());
end

rule "Enable ERS overtake"
when
    OvertakeOpportunity()
    BatteryHigh()
    not ErsOvertakeAvailable()
then
    insertLogical(new ErsOvertakeAvailable());
end

rule "Require suspension check after steering vibration"
when
    DriverReport(issue == DriverIssue.STEERING_VIBRATION)
    not SuspensionCheckRequired()
then
    insertLogical(new SuspensionCheckRequired());
end

rule "Detect possible suspension damage"
when
    SuspensionCheckRequired()
    SuspensionStatus(asymmetricCorneringGForces == true)
    not PossibleSuspensionDamage()
then
    insertLogical(new PossibleSuspensionDamage());
end

rule "Use all resources on final lap defense"
when
    RaceState(remainingLaps == 0)
    CompetitorStatus(driverBehindVeryClose == true)
    not FullResourceDefense()
then
    insertLogical(new FullResourceDefense());
end

rule "Detect weak car performance"
when
    TyresWorn()
    PaceDropDetected()
    not WeakCarPerformance()
then
    insertLogical(new WeakCarPerformance());
end
