package rules;

import com.ftn.sbnz.f1.model.enums.TrackCondition;
import com.ftn.sbnz.f1.model.enums.WeatherTrend;
import com.ftn.sbnz.f1.model.facts.DelayPitStopRecommended;
import com.ftn.sbnz.f1.model.facts.RainRiskWarning;
import com.ftn.sbnz.f1.model.facts.WeatherStatus;
import com.ftn.sbnz.f1.model.facts.WetEarlyPitRecommended;

rule "Recommend early pit for intensifying rain"
when
    WeatherStatus(trackCondition == TrackCondition.PARTIALLY_WET, weatherTrend == WeatherTrend.RAIN_INTENSIFYING)
    not WetEarlyPitRecommended()
then
    insertLogical(new WetEarlyPitRecommended());
end

rule "Recommend delaying pit while track is drying"
when
    WeatherStatus(trackCondition == TrackCondition.WET, weatherTrend == WeatherTrend.DRYING)
    not DelayPitStopRecommended()
then
    insertLogical(new DelayPitStopRecommended());
end

rule "Warn about rain risk on dry track"
when
    WeatherStatus(trackCondition == TrackCondition.DRY, rainProbabilityPercentage >= 60.0)
    not RainRiskWarning()
then
    insertLogical(new RainRiskWarning());
end
